
spring:

  datasource:
    druid:
       url: jdbc:mysql:///activiti?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
       username: root
       password: 123456
#       driver-class-name: com.mysql.cj.jdbc.Driver
   # type: com.alibaba.druid.pool.DruidDataSource
  activiti:
    #1.flase?????activiti????????????????????????????????????
    #2.true? activiti????????????????????????????
    #3.create_drop? ?activiti??????????????????????????????

    database-schema-update: true
    #????????? activiti7????????????? ?????????
    db-history-used: true
    #?????? ?????????none, activity, audit, full
    #none???????????????????????????????
    #activity?????none?????????????????????
    #audit??activity??????????????????????????audit?history?????
    #full??????????????????audit???????????????????????????????????
    history-level: full
    #???????????resources??processes?????????
    check-process-definitions: false
